export const chordsOptions: Record<string, string[]> = {
  major: ['I', 'ii', 'iii', 'IV', 'V', 'vi', 'vii°'],
  majorSevenths: ['Imaj7', 'iim7', 'iiim7', 'IVmaj7', 'V7', 'vim7', 'viiø7'],
  minor: ['i', 'ii°', 'bIII', 'iv', 'v', 'bVI', 'bVII'],
  minorSevenths: ['im7', 'iiø7', 'bIIImaj7', 'ivm7', 'vm7', 'bVImaj7', 'bVII7'],
  chromediants_major: ['I', 'bIII', 'III', 'bVI', 'VI'],
  chromediants_minor: ['i', 'biii', 'iii', 'bvi', 'vi'],
}

export const instrumentList = [
  'bass-electric',
  'bassoon',
  'cello',
  'clarinet',
  'contrabass',
  'flute',
  'french-horn',
  'guitar-acoustic',
  'guitar-electric',
  'guitar-nylon',
  'harmonium',
  'harp',
  'organ',
  'piano',
  'saxophone',
  'trombone',
  'trumpet',
  'tuba',
  'violin',
  'xylophone',
]
